# Generated by Django 5.2.8 on 2025-11-27 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['group__order', 'question_number_in_group', 'id']},
        ),
        migrations.AddField(
            model_name='question',
            name='question_number_in_group',
            field=models.IntegerField(default=1, help_text='Position of this question within its group (1-5 typically)'),
        ),
        migrations.CreateModel(
            name='QuestionGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Study the following line graph and answer questions 6-10'", max_length=500)),
                ('group_type', models.CharField(choices=[('number_series', 'Number Series'), ('line_graph', 'Line Graph'), ('bar_chart', 'Bar Chart'), ('pie_chart', 'Pie Chart'), ('table', 'Table/Data Interpretation'), ('missing_data', 'Missing Data Table'), ('puzzle', 'Puzzle (Floor/Flat/Arrangement)'), ('alphanumeric', 'Alphanumeric Series'), ('coding', 'Coding-Decoding'), ('seating', 'Seating Arrangement'), ('scheduling', 'Scheduling/Day Arrangement'), ('paragraph', 'Paragraph/Comprehension'), ('individual', 'Individual Question')], default='individual', max_length=20)),
                ('context_text', models.TextField(blank=True, help_text='Problem statement, table data, series pattern, or puzzle description')),
                ('context_image', models.ImageField(blank=True, help_text='Graph/chart/diagram image', null=True, upload_to='question_groups/')),
                ('order', models.IntegerField(default=0, help_text='Order of this group in the test')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_groups', to='exams.subject')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Question group this question belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='practice.questiongroup'),
        ),
    ]
