# Generated by Django 5.2.8 on 2025-11-26 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='total_marks',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='usertestattempt',
            name='correct_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertestattempt',
            name='skipped_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usertestattempt',
            name='wrong_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usertestattempt',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='UserTestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='tests.usertestattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.question')),
            ],
        ),
    ]
