# Generated by Django 5.2.8 on 2025-11-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_mocktest_difficulty_mocktest_total_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='exam_type',
            field=models.CharField(choices=[('SBI', 'SBI PO/Clerk'), ('IBPS', 'IBPS PO/Clerk'), ('RRB', 'RRB PO/Clerk')], default='SBI', max_length=10),
        ),
        migrations.AddField(
            model_name='mocktest',
            name='stage',
            field=models.CharField(choices=[('Prelims', 'Prelims'), ('Mains', 'Mains')], default='Prelims', max_length=10),
        ),
    ]
