# Generated by Django 5.2.8 on 2025-11-27 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_mocktest_exam_type_mocktest_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testquestion',
            options={'ordering': ['section__section_order', 'question__group__order', 'question__question_number_in_group', 'id']},
        ),
        migrations.AlterModelOptions(
            name='testsection',
            options={'ordering': ['section_order']},
        ),
        migrations.AddField(
            model_name='testquestion',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tests.testsection'),
        ),
        migrations.AddField(
            model_name='testsection',
            name='section_duration',
            field=models.IntegerField(default=20, help_text='Duration in minutes for this section'),
        ),
        migrations.AddField(
            model_name='testsection',
            name='section_name',
            field=models.CharField(default='Section', help_text="e.g., 'Numerical Ability', 'Reasoning Ability'", max_length=100),
        ),
        migrations.AddField(
            model_name='testsection',
            name='section_order',
            field=models.IntegerField(default=1, help_text='Order of this section in the test (1, 2, 3...)'),
        ),
        migrations.AlterField(
            model_name='mocktest',
            name='exam_type',
            field=models.CharField(choices=[('SBI', 'SBI Clerk'), ('IBPS', 'IBPS Clerk'), ('RRB', 'RRB Clerk')], default='SBI', max_length=10),
        ),
    ]
