# Generated by Django 5.2.8 on 2025-12-08 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_testquestion_options_alter_testsection_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocktest',
            name='is_generated',
            field=models.BooleanField(default=False, help_text='True if all questions are generated'),
        ),
    ]
