# Generated by Django 5.2.8 on 2025-12-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_mocktest_is_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mocktest',
            name='is_generated',
        ),
    ]
